### ISSUE TITLE
v0.1.0 fails with ModuleNotFoundError error

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#84]
When trying to run the version 0.1.0 with on Windows, macOS or Linux, we get this error message:

```
$ ./deposit --help
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources/__init__.py", line 90, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'
[5641] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

**Comment by valefar-on-discord** [comment]
related: https://github.com/pypa/setuptools/issues/4374
